theme: jekyll-theme-cayman
title: Compositeur Digital Documentation

defaults:
  # All pages have by default the "General" category, and no category link
  - scope:
      path: ""
      type: "pages"
    values:
      tags: ""
      category: "General"
      category_path: ""
      app_version: ""

# [ START ] Setting categories
  - scope:
      path: "UX"
      type: "pages"
    values:
      layout: default
      category: "UX"
      app_version: "UX"

  - scope:
      path: "V4"
      type: "pages"
    values:
      layout: default
      category: "V4"
      app_version: "V4"

  # [ START ] Setting language specific values
  # UX
  
  # fr
  - scope:
      path: "UX/fr"
      type: "pages"
    values:
      language: "fr"
      category_path: "/UX/fr"

  - scope:
      path: "UX/fr/organise_content"
      type: "pages"
    values:
      category_path: "/UX/fr/organise_content"
      category: "Organiser vos contenus"

  - scope:
      path: "UX/fr/organise_content/supported_content"
      type: "pages"
    values:
      category_path: "/UX/fr/organise_content/supported_content"
      category: "Contenu pris en charge"

  - scope:
      path: "UX/fr/organise_content/advanced_setting.md"
      type: "pages"
    values:
      tags: "Parametres avances"
      
  - scope:
      path: "UX/fr/organise_content/supported_providers.md"
      type: "pages"
    values:
      tags: "Fournisseurs de contenus"

  # en
  - scope:
      path: "UX/en"
      type: "pages"
    values:
      language: "en"
      category_path: "/UX/en"
      
  - scope:
      path: "UX/en/organise_content"
      type: "pages"
    values:
      category_path: "/UX/en/organise_content"
      category: "Organise content"

  - scope:
      path: "UX/en/organise_content/supported_content"
      type: "pages"
    values:
      category_path: "/UX/en/organise_content/supported_content"
      category: "Supported content"

  - scope:
      path: "UX/en/organise_content/advanced_setting.md"
      type: "pages"
    values:
      tags: "Advanced settings"
      
  - scope:
      path: "UX/en/organise_content/supported_providers.md"
      type: "pages"
    values:
      tags: "Content provider"

  # V4

  # fr
  - scope:
      path: "V4/fr"
      type: "pages"
    values:
      language: "fr"
      category_path: "/V4/fr"

  #en
  - scope:
      path: "V4/en"
      type: "pages"
    values:
      language: "en"
      category_path: "/V4/en"
  # [ END ] Setting language specific values

# [ END ] Setting categories
